### PR TITLE
Support DataJoint 2.x attribute-type spellings (backward compatible with 0.14.x)

### PR DESCRIPTION
**Pull request by akshay-jaggi**
Two attribute-type spellings used by this element were removed or changed in
DataJoint 2.x. All of them have replacements that work identically on 0.14.x, so this can
go in without waiting on a full 2.x migration.

### Why now

DataJoint **2.0.0** shipped 2026-02-03 and 2.3.2 is current. `install_requires`
here says `datajoint>=0.13`, so a fresh install today resolves 2.x and the
element cannot even be imported:

```
>>> import element_calcium_imaging.scan
AttributeError: module 'datajoint' has no attribute 'schema'. Did you mean: 'Schema'?
  element_calcium_imaging/scan.py:12   schema = dj.schema()
```

### What this changes

- `schema = dj.schema()` in `scan.py`, `imaging.py` and `imaging_report.py`
- `bidirectional : boolean` and `bidirectional_z=null : boolean` on `scan.ScanInfo`

| construct | 0.14.9 | 2.3.2 |
|---|---|---|
| `dj.schema` → `dj.Schema` | works — **literally the same object** in 0.14.9 | required; `AttributeError` at import |
| `boolean` → `bool` | works | required; `boolean` → `Unsupported attribute type` |

Verified by activating the element against MySQL under datajoint 0.14.9 and
2.3.2 in turn.

### What this deliberately does not change

`longblob`. It also has to change for 2.x — and much more urgently, because
under 2.x a `longblob` attribute silently stores `str(array)` rather than the
array — but `<blob>` is rejected by 0.14.9, so shipping it here would break
current users. It is on a separate branch and written up in the accompanying issue.

Applied mechanically with regexes rather than typed by hand, then reviewed. No
behaviour is changed, only spellings. Happy to reshape or split this however you
prefer.

### CODE REVIEW

**Comment by akshay-jaggi** [comment]
Added a fourth backward-compatible fix to this branch: **`dj.create_virtual_module` → `dj.VirtualModule`**, 5 call sites.

I missed it initially because I was sweeping for attribute-type spellings and this one is an API call. It turns out to be the one with the widest blast radius in this element — `imaging_report.py:30` calls it at module scope and `imaging.activate()` activates `imaging_report` *unconditionally*, so on DataJoint 2.x **every activation of the imaging element dies**, not just a plotting call:

```
AttributeError: module 'datajoint' has no attribute 'create_virtual_module'
  element_calcium_imaging/imaging_report.py:30
```

It is backward compatible more strongly than the other three changes here — in 0.14.9 `dj.create_virtual_module` **is** `dj.VirtualModule`, the same object with an identical signature:

```
dj 0.14.9
create_virtual_module: True   VirtualModule: True
cvm sig : (module_name, schema_name, *, create_schema=False, create_tables=False, connection=None, add_objects=None)
VM  sig : (self, module_name, schema_name, *, create_schema=False, create_tables=False, connection=None, add_objects=None)
same object: True
```

Found by driving `Scan → ScanInfo → ProcessingTask → Processing → MotionCorrection → Segmentation → Fluorescence → Activity` end to end in `task_mode='load'` against real suite2p output on DataJoint 2.3.2. With this fix plus the `longblob` → `<blob>` changes from the branch linked in #206, that whole chain populates and all 17 blob attributes across 9 tables fetch back as numpy arrays with the right dtype and shape.

**Comment by dimitri-yatsenko** [comment]
Thanks for this, and for the report in #206 — the diagnosis there is correct.
I traced it upstream and filed the DataJoint-side half as
https://github.com/datajoint/datajoint-python/issues/1527.

Good catch on `dj.create_virtual_module` → `dj.VirtualModule` as well — this is the
only element in the org that uses it, so nobody else would have hit it.

I'd like to redirect this PR rather than merge it.

**We are not keeping elements working on both 0.14.x and 2.x.** A schema is either
2.x or pre-2.x, the two are not interoperable, DataJoint no longer supports pre-2.x,
and all schemas should be migrated. So the constraint that kept `<blob>` off this
branch does not apply — please send the full migration as a single PR instead.

This is the most exposed element of the five, and the split is worst here. The
`boolean` attributes your PR fixes were the last remaining hard failure — after this
PR the element declares cleanly under 2.x with nothing left to stop it, and all **30**
`longblob` attributes silently corrupt on insert. The failures you removed are
currently the only thing preventing that.

### Remaining work for the full PR

| | count | |
|---|---|---|
| `longblob` → `<blob>` | 30 | the data-loss fix |
| `int` / `smallint` → `int32` / `int16` | 24 | works today, but native; warns |
| `float` → `float32` | 23 | same |

Also raise the DataJoint floor — `setup.py` `datajoint>=0.14.0` → `datajoint>=2.3`. That unpinned floor is
the root cause: it is what makes a fresh install resolve 2.x in the first place.

Please work from the migration guide rather than from this comment — it is the
authoritative version: **[Migrate to DataJoint 2.0](https://docs.datajoint.com/how-to/migrate-to-v20/)**.
It covers the legacy → 2.0 type mapping (`longblob` → `<blob>`, `attach` → `<attach>`,
and the `@store` variants), the `:<blob>:` column-comment marker that is the mechanism
behind the bug, the four-phase structure, and the case for creating tests before
migrating. What you have on your branch is Phase I — code only, against empty `_v2`
schemas, no impact on existing data. Migrating existing data is Phase III and separate.

This repo does have a `tests/` directory, which puts it ahead of its siblings — please
extend it to cover the converted types.

Happy to review the full 2.x PR as soon as you open it. I'd suggest closing this one in
favour of that, or reusing this branch and pushing the rest onto it — your call, leaving
it open for you to decide.
